### ISSUE TITLE
O código possui problemas

### ISSUE THREAD

**Issue by AllanSmithll** [oiclai/CRE-Calculator#1]
Achei o repositório interessante, por isso favoritei. Existem dois problemas no cálculo, mas não sei se você já percebeu:

1. Ele só devolve o valor da última nota informada;
2. Deveria arredondar para duas casas decimais, como é o CRE.

**Comment by oiclai** [comment]
Realmente! Me faltou atenção nisso. Já fiz as alterações que recomendou.
